### ISSUE TITLE
pro series keeps updating

### ISSUE THREAD

**Issue by wimwijn01** [martin-lueders/ML_Pro_Series#2]
pro series keeps updating, (red dot), but backwards to 6.0, manager says 6.1,

**Comment by martin-lueders** [comment]
Can you, please, give me some more information? Which platform are you on (Mac/PC)?
Did you try to delete the ML_modules_QU and ML_modules_seq folders completely, and then see wether the update goes through?

**Comment by wimwijn01** [comment]
Hi Martin, everything fine now, after deleting everything the update went good and no "red dot"anymore. It was strange because I did have the pro series for a while and at once they started to update/downgrade
thanks for the quick reaction
Wim
