### ISSUE TITLE
Quantum Multiverse Ignores 0.00 Input

### ISSUE THREAD

**Issue by midiguru23** [martin-lueders/ML_Pro_Series#4]
I've confirmed this. Whenever a step sequencer sends 0.00 to Quantum Multiverse, the output value does not change from whatever it was previously. I'll attach a very simple patch that illustrates this. Watch the values in the Nysthi Const Add Mult to see the problem. (Attaching as .txt because the github interface doesn't support .vcv.)

[quantum_multiverse_00_bug.txt](https://github.com/martin-lueders/ML_Pro_Series/files/2632233/quantum_multiverse_00_bug.txt)

**Comment by martin-lueders** [comment]
OK. I can confirm the bug and will have a look into it. I will keep you updated.
Thanks for reporting it.

**Comment by martin-lueders** [comment]
This should be fixed now in the new version.
